### ISSUE TITLE
UX/Design help

### ISSUE THREAD

**Issue by flacozacarias** [warmshowers/warmshowers-iphone-app#19]
Hi, I'm a web designer and WS member. I just exchanged a couple of emails with Randy and I'd like to offer help, if you need. Please let me know. Thanks

**Comment by chriscdn** [comment]
Hi @flacozacarias:  Thanks for your note.  Let me just do a high-level review of things.  Please ask if anything isn't clear...

There are a few design issues I'm uncertain on.  I'm trying hard to stick to the [iOS Human Interface Guidelines](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/) as it makes it much easier to keep things forwards compatible and working among all device types (iPhone 5, 6, 6+, iPad).

The primary purpose of the app is to find hosts.  For that reason I made the map the default view as it's likely the starting point for any search.

The Host View could probably use a revisit.  The view is quite long (especially with all the Max Guest, Motel, Camping, Bike Shop, etc. fields) and some functions are buried in the menu (the button top-right).  Many users seem to miss this and I'm thinking many of these functions could be somehow put into the main view.

The second major design issue is building in a messaging app to send and receive messages.  This is separate to the searching of hosts, so I thought of using a [tabbed view](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/TabBarControllers.html) or one of those side views that have become popular in the last years (let me know if that's not clear).

Of course, I'm open to any other general UI improvements that you can recommend.

Thanks!

**Comment by flacozacarias** [comment]
Hi Christopher, 
thanks for the info! I just checked the app again (I have iPhone 4S, with iOS8) and I see what you mean. Let me think of some solutions, take some screenshots and get back to you ASAP. Hopefully in two days, if not, early next week after a quick bike weekend trip. Thanks!

Flaco Zacarias

» http://www.zacarias.com
» flaco@zacarias.com
» @flaco_zacarias
» (+49) 151 6123 7906

**Comment by flacozacarias** [comment]
Hi Christopher, 
I’m finally here with my review. I see your concerns and yes, agree that the menu button gets lost a bit. 

The Contact Host button could be inside the view, after a few options. If you’d like, I can prepare some quick mockups with photoshop so we can check some options.

To me, what’s missing here is a cover/intro page, right before the map, telling a bit about how it works. Something very simple. I can work on that too if you’d like. 

A chat function would be nice and somehow will need to coexist with email message function. Have you thought how to make that happen, from a user perspective? I’m thinking that maybe the first message goes to email without delay and, if the replies are quick (let’s say, less than 30 minutes) they’re kept in the messenger. Kind of like what Facebook does: If i write to a friend I get an email after half hour but if instead of writing on the messenger app we chat, then I don’t get the email notifications. Is that clear? Does it makes sense? Is that doable? Let me know. 
Thanks!

Flaco Zacarias

» http://www.zacarias.com
» flaco@zacarias.com
» @flaco_zacarias
» (+49) 151 6123 7906
