### ISSUE TITLE
Cryptographic Export Certification

### ISSUE THREAD

**Issue by chriscdn** [warmshowers/warmshowers-iphone-app#23]
Apps that use encryption (including https) must be registered and certified with the US Department of Commerce.  This must be done for the warmshowers iOS app that uses https.

**Comment by paul-delange** [comment]
Actually you don't need to do this if your source code is publicly available. It's one of the exceptions.

**Comment by chriscdn** [comment]
@paul-delange Thank you...  I did notice this when registering a different app but didn't connect the dots to the warmshowers app.  Cheers.
