### ISSUE TITLE
Feedback count is incorrect (and no feedback available for display)

### ISSUE THREAD

**Issue by rfay** [warmshowers/warmshowers-iphone-app#25]
In the latest build (541), it shows "View Feedback (0)" for all members.  When you click, it shows no feedback even for members with plenty of feedback.

**Comment by chriscdn** [comment]
@rfay This is happening because `/user/####/json_recommendations` has the following in the response:

    Content-Type:$content_type; charset=utf-8

This should be:

    Content-Type: application/json; charset=utf-8

**Comment by rfay** [comment]
Will see if I can fix that this afternoon. A thorn in your side this
content type stuff!

Thanks for all your work on this.

**Comment by rfay** [comment]
Works fine now in my iPad. Thanks for the debugging.
