### ISSUE TITLE
SSL Trust 

### ISSUE THREAD

**Issue by RajanFernandez** [warmshowers/warmshowers-iphone-app#39]
From iOS 10.3, the warmshowers.org SSL certificate is not natively trusted (https://support.apple.com/en-nz/HT207177) and so all API calls are blocked by the URLSessionDelegate. Hence the app is currently broken for all iPhone users with iOS 10.3+.
The relevant delegate method can be implemented to trust the warmshowers domain automatically.

**Comment by chriscdn** [comment]
I just tried it with iOS 10.3.2 and it seemed to work fine.  How would I test this?

**Comment by RajanFernandez** [comment]
Strange. This has not worked for the past week on iOS 10.3.2 devices and also with the iOS 11 beta. Foundation was returning an SSL trust error. Another Warmshowers member also contacted me about this issue. 
Now it seems to work fine. Maybe the SSL certificates have been updated on the server?
Will close this issue.
