### ISSUE TITLE
iOS app not available in app storep

### ISSUE THREAD

**Issue by komape** [warmshowers/warmshowers-iphone-app#40]
There is no warmshowers app available in the iOS app store. 

I just deleted the app on my phone because it was so buggy. Then I wanted to reinstall it but it can’t be found. 

What is the reason for that? I mean there was an app, why just don’t keep it in the store?

**Comment by RajanFernandez** [comment]
The Warmshowers committee decided that the current mobile apps would no longer be supported in favor of the mobile website. There have been some announcements on the Facebook page over the last or so regarding this. You could contact the website support team for more info.

**Comment by komape** [comment]
That's really bad. [Opened new issue for the website](https://github.com/warmshowers/Warmshowers.org/issues/1036).

**Comment by mlthlschr** [comment]
maybe this repo can be archived then. 
Moreover all the references of the app on the warmshowers website should be removed or the obsolescence should be mentioned somewhere there (who uses facebook in the first place).
